language: julia
os:
    - linux
julia:
    - 1
notifications:
    email: false
sudo: false
addons:
    ssh_known_hosts: github.com
    apt_packages:
        - gfortran
        - liblapack-dev
        - libblas-dev
env:
  global:
  - secure: rVoIRTheBcPJ7Sytnvu8pje0Qds4ekWmdb7cEI0rRE+8s4+4M4aNjExjTQsDgFph10L/O5FCVwDP0EgmUWzU2zmZ4HsR7rLEDp5obzhHWX6qS04xFXiZUrwNjLaP01k+BUMDNsAJprXJ00Q7jCucPCWokKp4fPFZWRxOp8cmStWeVbDemnbHJGJlqqnFre1sL9g6MOQHue9fGN39d/LDU/9bkXHjuk4WooeMTohXzJT7KoKtC9PAv9+5j5Sup5nRySlJaTj/pc0iAHRwHafE6pK4d6jIgl/RPy9oqjahqhVtfO7DcUxmpcuYliQgpJknWZkKhIG4+o7jaWftQcpBAIJPK2XYsUXVDs2TDwoJc4jlkoq3WZ+LOqagx7zaCYM9cSEZ1Uj8EXE0sp/6brEshoOH8tIjvHNegii2tEkWrsQXHD/Lqhvso6gNOCu7u3826s2QjuygsgUR70tJGKYBqZTp4D07UIQu8/SDLSRl7MlpcE2r2Wqkiaic1+h/EUOiy0CD9LVGbC40qtsp0PHDOp8R60PwqIWO882TRA+65roCB3o/Lic9OzvAFuiyPihEsqA4xBOGp6xPKA9ALSRaxNq0OfUXLcdihNApSDNySDo9g1e7Y78WH6p9co3q0/+d8E6dC/Tvpci2fepfKC6izVJhx9oAdV1P04pJdVrZcsw=
script:
- julia -e 'const PACKAGE = ENV["PACKAGE"]; using Pkg; Pkg.develop("MathOptInterface"); Pkg.develop(PACKAGE); Pkg.test(PACKAGE)'
jobs:
  include:
    - env: PACKAGE=Tulip
    - env: PACKAGE=Xpress
      os:  osx
before_install:
  - wget -q $FILES
  - eval "$(ssh-agent -s)"
  - chmod 600 xpress_binkey
  - ssh-add xpress_binkey
  - git clone -v git@github.com:jd-lara/XPRESSBINFILES.git $HOME/XPRESSBINFILES
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then
      export XPRESSDIR=$HOME/XPRESSBINFILES/xpressmp_mac;
      export DYLD_LIBRARY_PATH=$XPRESSDIR/lib:$DYLD_LIBRARY_PATH;
    fi;
  - if [[ $TRAVIS_OS_NAME == "windows" ]]; then
      XPRESSDIR=$HOME/XPRESSBINFILES/xpressmp_win;
    fi;
